name: Automate extraction

on: 
  schedule: 
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      URL_SKILLS: ${{secrets.URL_SKILLS}}
    steps:
      - uses: actions/checkout@v4  
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.3' 
      - run: pip install -r requirements.txt
      - run: python main.py
