name: Automate extraction

on: 
  schedule: 
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      URL_SKILLS: ${{secrets.URL_SKILLS}}
      URL_JOBS: ${{secrets.URL_JOBS}}
    steps:
      - uses: actions/checkout@v4  
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - run: sudo apt-get update && sudo apt-get install -y libpq-dev build-essential
      - run: pip install -r requirements.txt
      - run: python main.py
