name: Automate extraction

on: 
  push:
  schedule: 
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      URL_SKILLS: ${{secrets.URL_SKILLS}}
      URL_JOBS: ${{secrets.URL_JOBS}}
      POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DATABASE: ${{secrets.POSTGRES_DATABASE}}
      POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
      POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
    steps:
      - uses: actions/checkout@v4  
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Install dependencies de SO
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable unzip
      - uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: 'latest'
      - run: sudo apt-get update && sudo apt-get install -y libpq-dev build-essential
      - run: pip install -r requirements.txt
      - run: python main.py
